name: Scan with BlackDuck
description: Scans the project with BlackDuck

inputs:
  blackduck_token:
    description: The token to use for BlackDuck authentication
    required: true
  github_token:
    description: The token to use for GitHub authentication
    required: true
  java-version:
    description: The version of Java to use
    default: "17"
    required: false
  maven-version:
    description: The Maven version the build shall run with.
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java ${{ inputs.java-version }}
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: sapmachine
        cache: maven

    - name: Set up Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Get Major Version
      id: get-major-version
      run: |
        echo "REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print Version Number
      run: echo "${{ steps.get-major-version.outputs.REVISION }}"
      shell: bash

    - name: BlackDuck Scan
      uses: SAP/project-piper-action@main
      with:
        step-name: detectExecuteScan
        flags: \
          --version=${{ steps.get-major-version.outputs.REVISION }}
      env:
        PIPER_token: ${{ inputs.blackduck_token }}
        PIPER_githubToken: ${{ inputs.github_token }}
        SCAN_MODE: FULL
