name: Scan with SonarQube
description: Scans the project with SonarQube

inputs:
  sonarq-token:
    description: The token to use for SonarQube authentication
    required: true
  github-token:
    description: The token to use for GitHub authentication
    required: true
  java-version:
    description: The version of Java to use
    required: true
  maven-version:
    description: The version of Maven to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Java ${{inputs.java-version}}
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        java-version: ${{inputs.java-version}}
        distribution: sapmachine
        cache: maven

    - name: Set up Maven ${{inputs.maven-version}}
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: ${{inputs.maven-version}}

    - name: Get Revision
      id: get-revision
      run: |
        echo "REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print Revision
      run: echo "${{steps.get-revision.outputs.REVISION}}"
      shell: bash

    - name: SonarQube Scan
      uses: SAP/project-piper-action@main
      with:
        step-name: sonarExecuteScan
        flags: --token=${{inputs.sonarq-token}} --githubToken=${{inputs.github-token}} --version=${{steps.get-revision.outputs.REVISION}} --inferJavaBinaries=true
